name: Sonatype Lifecycle SCA Scan

on:
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    # if: github.repository_owner == 'finos'
    # strategy:
    #   matrix:
    #     configuration: [Debug] #Release

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Sonatype-SCA # Replace with your solution name, i.e. MyWpfApp.sln.
      SonatypeCLIUrl: https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/scanner/nexus-iq-cli-1.182.0-01+864-windows.zip
      SonatypeUrl: 'https://finos.sonatype.app/platform/'
      SonatypeAppId: 'morphir-dotnet'
      SonatypeStage: ${{ github.job }}
      SonatypeScanTarget: "."
      ExcludeDirectory: " -D dirExcludes='**/website/, **/docs/, **/.*'"
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Resolve Paket Dependencies
      run: |
        dotnet tool install --global Paket
        dotnet tool restore
        paket install
        .\build.cmd DotnetRestore
        
    - name: Create CycloneDX SBOM (transitive mapping)
      run: |
         dotnet tool install --global CycloneDX
         dotnet restore
         copy build/build.fsproj SonatypeSCA.csproj
         dir
         echo $env:SBOM_Path
         dotnet CycloneDX SonatypeSCA.csproj -o packages/
    
    - name: Download and Scan with Sonatype Lifecycle CLI
      if: always()
      run: |
         echo Sonatype-CLI.jar - {{ env.SonatypeCLIUrl }}
         curl --location ${{ env.SonatypeCLIUrl }} > Sonatype.zip
         tar -xf Sonatype.zip
         rm Sonatype.zip
         .\nexus-iq-cli.exe -s ${{ env.SonatypeUrl }} -a ${{ secrets.SONATYPE_SCANNER_USERNAME }}:${{ secrets.SONATYPE_SCANNER_PASSWORD }} -t ${{ env.SonatypeStage }} ${{ env.ExcludeDirectory }} -r sonatype-results.json -i ${{ env.SonatypeAppId }} ${{ env.SonatypeScanTarget }}

    - name: Upload Sonatype Scan Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SonatypeAppId }} Sonatype Scan Results 
        path: sonatype-results.json
